### ISSUE TITLE
Additional fields needed in `field_schema.yml`

### ISSUE THREAD

**Issue by Beck-Davis** [pulibrary/marc_cleanup#109]
Acceptance criteria:

- [x] Add the following fields and their indicators, subfields, and repeatability of field and subfields to `field_schema.yml`
  - [x] 092 (See https://www.oclc.org/bibformats/en/0xx/092.html)
  - [x] 886 (See https://www.loc.gov/marc/bibliographic/bd886.html)

**Comment by pmgreen** [comment]
@mzelesky does 886 need to be adjusted?

**Comment by mzelesky** [comment]
Wow, good catch. Yes, the 886 needs to be adjusted. This one is tricky.

They are all repeatable subfields due to the dual nature of the field.

So,
`$a` should have a description of `Tag of the foreign MARC field / Foreign MARC subfield`
`$b` should have a description of `Content of the foreign MARC field / Foreign MARC subfield`
`$2` should have a description of `Source of data / Foreign MARC subfield`

The rest of the numerical subfields should just have a description of `Foreign MARC subfield`
